name: Build and Test

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  ROS_DISTRO: galactic

jobs:
  ci:
    name: build-and-push-galactic
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      # - name: Login to Github Packages
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # create and boot a builder using by default the docker-container builder driver.
      # This is not required but recommended using it to be able to build multi-platform images, export cache, etc.
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:galactic"
